#!/usr/bin/env bash

# fetch raw data
fetchdata() {
  curl -s http://www.football-data.co.uk/mmz4281/1718/I2.csv -o i2
}
# fetch data if missing
[[ -f i2 ]] || fetchdata
# clean data
games=$(awk '
BEGIN{FS=OFS=","}; NR >= 2 {split($2, a, "/"); print 20a[3] a[2] a[1],$3,$4,$5,$6,$7}
' i2 | tac)
# home draws
home=$(cut -d, -f2,6 <(echo "$games") | grep ,D | cut -d, -f1| sort | uniq -c | sort -r)
# away draws
away=$(cut -d, -f3,6 <(echo "$games") | grep ,D | cut -d, -f1| sort | uniq -c | sort -r)
# teams
mapfile -t teams < <(cut -d, -f2 <(echo "$games") | sort | uniq)

lastgames() {
  last5=$(echo "$games" | grep -i "$1" -m5)
  awk -v team="$1" '
  BEGIN{FS=IFS",";IGNORECASE=1;}
  {
    if ($6=="D") strike=strike"D";
    else if (($6=="H" && $2==team) || ($6=="A" && $3==team)) strike=strike"W";
    else strike=strike"L";
  }
  END{print team" last five games: "strike}
  ' <(echo "$last5")
}	# ----------  end of function lastgames  ----------

lasthome() {
  last5=$(echo "$games" | cut -d, -f2,6 | grep -i "$1" -m5)
  awk -v team="$1" '
  BEGIN {FS=IFS=","}
  {
    if ($2=="D") strike=strike"D";
    else if ($2=="H") strike=strike"W";
    else strike=strike"L";
  }
  END{print team" last five home games: "strike;}
  ' <(echo "$last5")
}	# ----------  end of function lasthome  ----------

lastaway() {
  last5=$(echo "$games" | cut -d, -f3,6 | grep -i "$1" -m5)
  awk -v team="$1" '
  BEGIN {FS=IFS=",";IGNORECASE = 1;}
  {
    if ($2=="D") strike=strike"D";
    else if ($2=="A") strike=strike"W";
    else strike=strike"L";
  }
  END{print team" last five away games: "strike;}
  ' <(echo "$last5")
}	# ----------  end of function lastaway  ----------

allteamsallgames() {
  for t in "${teams[@]}"
  do
    lastgames "$t"
    # other stuff on $name
  done
}	# ----------  end of function all games ----------

allteamshomegames() {
  for t in "${teams[@]}"
  do
    lasthome "$t"
    # other stuff on $name
  done
}	# ----------  end of function all home  ----------

allteamsawaygames() {
  for t in "${teams[@]}"
  do
    lastaway "$t"
    # other stuff on $name
  done
}	# ----------  end of function all away  ----------

case "$1" in
  d) fetchdata ;;
  h) echo "$home" ;;
  a) echo "$away" ;;
  l) lastgames "$2" ;;
  lh) lasthome "$2" ;;
  la) lastaway "$2" ;;
  t) allteamsallgames ;;
  th) allteamshomegames ;;
  ta) allteamsawaygames ;;
  *) echo "$games" ;;
esac    # --- end of case ---
